import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Passion_One } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--poppins-font",
});

const passionOne = Passion_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--passion-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${passionOne.variable} bg-primary-900 text-secondary-900 font-poppins`}
      >
        {children}
      </body>
    </html>
  );
}
